/* Deepak's Punjabi Songs: 35 top trending hits (2024-2026), YouTube IDs verified via official channels/kworb. */
window.SONGS = [
{title:'Wavy',artist:'Karan Aujla',year:2024,era:'2020s',youtubeIds:['jQ0h0ce5wi8'],sourceType:'Karan Aujla official'},
{title:'410',artist:'Sidhu Moose Wala',year:2024,era:'2020s',youtubeIds:['F9gq_0HXoRI'],sourceType:'Sidhu Moose Wala official'},
{title:'Gurl',artist:'Jassa Dhillon ft. Harnoor',year:2024,era:'2020s',youtubeIds:['5mb9j7QTMLU'],sourceType:'official video'},
{title:'Tu Juliet Jatt Di',artist:'Diljit Dosanjh',year:2024,era:'2020s',youtubeIds:['CXL8De-xk7c'],sourceType:'Jatt & Juliet 3 official'},
{title:'Winning Speech',artist:'Karan Aujla',year:2024,era:'2020s',youtubeIds:['CHMtAdZ5YVs'],sourceType:'Karan Aujla official'},
{title:'Tauba Tauba',artist:'Karan Aujla (Bad Newz)',year:2024,era:'2020s',youtubeIds:['LK7-_dgAVQE'],sourceType:'Saregama Music'},
{title:'Aaye Haaye',artist:'Karan Aujla x Nora Fatehi x Neha Kakkar',year:2024,era:'2020s',youtubeIds:['uChhQpHMmXE'],sourceType:'T-Series'},
{title:'Drippy',artist:'Sidhu Moose Wala',year:2024,era:'2020s',youtubeIds:['5ZKLM5pNoGQ'],sourceType:'Sidhu Moose Wala official'},
{title:'Old Money',artist:'AP Dhillon ft. Salman Khan',year:2024,era:'2020s',youtubeIds:['-K-WY0WRT48'],sourceType:'official video'},
{title:'MVP',artist:'Shubh',year:2024,era:'2020s',youtubeIds:['2ycBQZslu8M'],sourceType:'Shubh official'},
{title:'Attach',artist:'Sidhu Moose Wala x Steel Banglez ft. Fredo',year:2024,era:'2020s',youtubeIds:['t14j6XVGCSo'],sourceType:'official video'},
{title:'Kufar',artist:'Diljit Dosanjh ft. Manushi Chhillar',year:2025,era:'2020s',youtubeIds:['WVq1siHnPxI'],sourceType:'official video'},
{title:'Charmer',artist:'Diljit Dosanjh ft. Sanya Malhotra',year:2025,era:'2020s',youtubeIds:['CGhGAVH2GqY'],sourceType:'official video'},
{title:'Boyfriend',artist:'Karan Aujla ft. Sunanda',year:2025,era:'2020s',youtubeIds:['5GCfYLguTIs'],sourceType:'Karan Aujla official'},
{title:'MF GABHRU',artist:'Karan Aujla',year:2025,era:'2020s',youtubeIds:['Fbv6-50S1lc'],sourceType:'Karan Aujla official'},
{title:'Supreme',artist:'Shubh',year:2025,era:'2020s',youtubeIds:['fgbcH5DkUsk','AX1zRInC_TA'],sourceType:'Shubh official'},
{title:'Balenci',artist:'Shubh',year:2025,era:'2020s',youtubeIds:['nt5tXl9Vtug'],sourceType:'Shubh official'},
{title:'Barota',artist:'Sidhu Moose Wala',year:2025,era:'2020s',youtubeIds:['XpF9_3qih4k'],sourceType:'Sidhu Moose Wala official'},
{title:'Lock',artist:'Sidhu Moose Wala',year:2025,era:'2020s',youtubeIds:['_wfrNbLguWw'],sourceType:'Sidhu Moose Wala official'},
{title:'Take Notes',artist:'Sidhu Moose Wala',year:2025,era:'2020s',youtubeIds:['EdxguQAXeoU'],sourceType:'Sidhu Moose Wala official'},
{title:'0008',artist:'Sidhu Moose Wala',year:2025,era:'2020s',youtubeIds:['uKAPYLvDJFQ'],sourceType:'Sidhu Moose Wala official'},
{title:'Neal',artist:'Sidhu Moose Wala',year:2025,era:'2020s',youtubeIds:['TP0pxZ1EszM'],sourceType:'Sidhu Moose Wala official'},
{title:'Aadat',artist:'Yo Yo Honey Singh ft. AP Dhillon',year:2025,era:'2020s',youtubeIds:['lcw4TDMBjZA'],sourceType:'official video'},
{title:'Together',artist:'Shubh',year:2025,era:'2020s',youtubeIds:['7iy8iB8tu5c'],sourceType:'Shubh official'},
{title:'Pan India',artist:'Guru Randhawa',year:2025,era:'2020s',youtubeIds:['e2l7t1dzE8g'],sourceType:'official video'},
{title:'Kithe Vasde Ne',artist:'Guru Randhawa',year:2025,era:'2020s',youtubeIds:['TUuTzp8Tmu0'],sourceType:'Guru Randhawa official'},
{title:'ACE',artist:'Shubh',year:2026,era:'2020s',youtubeIds:['o-iWYlgdUHw'],sourceType:'Shubh official'},
{title:'Bounce',artist:'Shubh',year:2026,era:'2020s',youtubeIds:['yi-P8HCFtyw'],sourceType:'Shubh official'},
{title:'Moves',artist:'Shubh',year:2026,era:'2020s',youtubeIds:['w-tlQtHWJt4'],sourceType:'Shubh official'},
{title:'5-7',artist:'Karan Aujla',year:2026,era:'2020s',youtubeIds:['omWV2zs1B2I'],sourceType:'Karan Aujla official'},
{title:'Ranjha',artist:'Diljit Dosanjh ft. Sia & David Guetta',year:2026,era:'2020s',youtubeIds:['fTpKWImEx84','9wTEmuv6SvU'],sourceType:'official video'},
{title:'Dealer',artist:'Diljit Dosanjh',year:2026,era:'2020s',youtubeIds:['YwtvQ23_-34'],sourceType:'official video'},
{title:'Eyes On Me',artist:'Sidhu Moose Wala',year:2026,era:'2020s',youtubeIds:['VDx-vTEIozA'],sourceType:'Sidhu Moose Wala official'},
{title:'DOPAMINE',artist:'Guru Randhawa',year:2026,era:'2020s',youtubeIds:['S73QCB1PF6s'],sourceType:'Guru Randhawa official'},
{title:'Headliner',artist:'Navaan Sandhu',year:2026,era:'2020s',youtubeIds:['GE6w7DRyqcM'],sourceType:'official video'},
];
