window.SONGS = [
{title:"Tere Tille Ton",artist:"Kuldeep Manak",year:1980,era:"80s",youtubeIds:["xpu4TyohMVA"]},
{title:"Ik Kudi Jihda Naam Mohabbat",artist:"Shiv Kumar Batalvi",year:1980,era:"80s",youtubeIds:["7KrJpJlHqRM"]},
{title:"Putt Jattan De",artist:"Surinder Shinda",year:1981,era:"80s",youtubeIds:["oUDCr6auJ8w","tdLLucR6wlM"]},
{title:"Jind Mahi",artist:"Surinder Shinda",year:1980,era:"80s",youtubeIds:["ceQfgU062jY","Z9IoFMdmsoA"]},
{title:"Challa",artist:"Gurdas Maan",year:1983,era:"80s",youtubeIds:["Nfa0oXVAs3U","I0lsDLbH1TI"]},
{title:"Dil Da Mamla Hai",artist:"Gurdas Maan",year:1984,era:"80s",youtubeIds:["DuAKzZGcc1A","jiwKVciHJxM","Fp0WEiptu2o"]},
{title:"Mitra Ne Dil Mangeya",artist:"Kuldeep Manak",year:1980,era:"80s",youtubeIds:["Y0-uxXH7ePk"]},
{title:"Yaar Mera Titliyan Warga",artist:"Surinder Kaur",year:1970,era:"70s",youtubeIds:["oy-khB66u38"]},
{title:"Jutti Kasuri",artist:"Surinder Kaur",year:1970,era:"70s",youtubeIds:["i61jXn-x91k"]},
{title:"Sada Chirhiyan Da Chamba",artist:"Narinder Biba",year:1975,era:"70s",youtubeIds:["Q-hs-X59g2A","vbB5scfDOVA"]},
{title:"Ki Banu Duniya Da",artist:"Gurdas Maan",year:1989,era:"80s",youtubeIds:["9yEP5yYpcJY","pjQyBF2gwjQ"]},
{title:"Apna Punjab Hove",artist:"Gurdas Maan",year:1990,era:"90s",youtubeIds:["1cHLSWmVnTE"]},
{title:"Lak Hile Majajan Jandi Da",artist:"Surinder Kaur & Harcharan Garewal",year:1987,era:"80s",youtubeIds:["zjJGWhjtecs"]},
{title:"Pehle Lalkare Naal",artist:"Amar Singh Chamkila & Amarjot",year:1980,era:"80s",youtubeIds:["WuaWe0g-xL8","6RzI-dwdCEA","l1SYRf0DZL0"]},
{title:"Baba Tera Nankana",artist:"Amar Singh Chamkila & Amarjot",year:1980,era:"80s",youtubeIds:["lJ2_pKXOfGI","O9XfPHvGk1M"]},
{title:"Mera Pind",artist:"Hans Raj Hans",year:1993,era:"90s",youtubeIds:["fSY9z9G2QW8"]},
{title:"Challa",artist:"Mohammed Sadiq",year:1980,era:"80s",youtubeIds:["boK2M8BtihE"]},
{title:"Madhaniyan",artist:"Neha Bhasin",year:1990,era:"90s",youtubeIds:["UFYSJ5arOyE"]},
{title:"Kali Teri Gut",artist:"Asa Singh Mastana",year:1970,era:"70s",youtubeIds:["liq3x6G__2w"]},
{title:"Jugni",artist:"Alam Lohar",year:1975,era:"70s",youtubeIds:["EW2eZS_02Jk","_nipggVkaD8"]},
{title:"Akhiyan De Kol",artist:"Reshma",year:1990,era:"90s",youtubeIds:["V_gd6uiXbjs"]},
{title:"Mera Laung Gawacha",artist:"Noor Jehan",year:1980,era:"80s",youtubeIds:["wqifi6g2rWc","i3lqY2YCPgk"]},
{title:"Nachdi Di Gooth",artist:"Premi",year:1987,era:"80s",youtubeIds:["pqgyGp5sucI","S4O_LAeCWcQ","lrVeGpjLZ7Q"]},
{title:"Ho Jayegi Balle Balle",artist:"Daler Mehndi",year:1995,era:"90s",youtubeIds:["ymo3lvQEqhM"]},
{title:"Tunak Tunak Tun",artist:"Daler Mehndi",year:1998,era:"90s",youtubeIds:["WfNnAIjNV6A"]},
{title:"Gur Nalon Ishq Mitha",artist:"Malkit Singh",year:1990,era:"90s",youtubeIds:["OAKag1aFDy8"]},
{title:"Mundian To Bach Ke",artist:"Panjabi MC",year:1998,era:"90s",youtubeIds:["x9WO2ieJMYk"]},
{title:"Kangna",artist:"Dr Zeus",year:2003,era:"2000s",youtubeIds:["ua_jvj9dZJQ"]},
{title:"Mitran Di Chhatri",artist:"Babbu Maan",year:2001,era:"2000s",youtubeIds:["ioWkx6WRH2I"]},
{title:"Sohniye",artist:"Harbhajan Mann",year:2000,era:"2000s",youtubeIds:["7H0u8N6hN0E","dYc-E91orEM"]}
];
