/* Deepak's Punjabi Songs — trending hits 2024–2026.
   YouTube IDs point to official channels/labels only (verified). */
window.SONGS = [
  { title: "Wavy", artist: "Karan Aujla", year: 2024, youtubeIds: ["jQ0h0ce5wi8"] },
  { title: "410", artist: "Sidhu Moose Wala", year: 2024, youtubeIds: ["F9gq_0HXoRI"] },
  { title: "Tu Juliet Jatt Di", artist: "Diljit Dosanjh", year: 2024, youtubeIds: ["CXL8De-xk7c"] },
  { title: "Winning Speech", artist: "Karan Aujla", year: 2024, youtubeIds: ["CHMtAdZ5YVs"] },
  { title: "Tauba Tauba", artist: "Karan Aujla (Bad Newz)", year: 2024, youtubeIds: ["LK7-_dgAVQE"] },
  { title: "Aaye Haaye", artist: "Karan Aujla x Nora Fatehi", year: 2024, youtubeIds: ["uChhQpHMmXE"] },
  { title: "Old Money", artist: "AP Dhillon ft. Salman Khan", year: 2024, youtubeIds: ["-K-WY0WRT48"] },
  { title: "MVP", artist: "Shubh", year: 2024, youtubeIds: ["2ycBQZslu8M"] },
  { title: "Bora Bora", artist: "AP Dhillon ft. Ayra Starr", year: 2024, youtubeIds: ["xARHpBzxFNI"] },
  { title: "Drippy", artist: "Sidhu Moose Wala", year: 2024, youtubeIds: ["5ZKLM5pNoGQ"] },
  { title: "Attach", artist: "Sidhu Moose Wala x Steel Banglez", year: 2024, youtubeIds: ["t14j6XVGCSo"] },
  { title: "Gurl", artist: "Jassa Dhillon ft. Harnoor", year: 2024, youtubeIds: ["5mb9j7QTMLU"] },
  { title: "Kufar", artist: "Diljit Dosanjh ft. Manushi Chhillar", year: 2025, youtubeIds: ["WVq1siHnPxI"] },
  { title: "Charmer", artist: "Diljit Dosanjh ft. Sanya Malhotra", year: 2025, youtubeIds: ["CGhGAVH2GqY"] },
  { title: "Boyfriend", artist: "Karan Aujla ft. Sunanda", year: 2025, youtubeIds: ["5GCfYLguTIs"] },
  { title: "M.F. GABHRU", artist: "Karan Aujla", year: 2025, youtubeIds: ["Fbv6-50S1lc"] },
  { title: "Supreme", artist: "Shubh", year: 2025, youtubeIds: ["fgbcH5DkUsk", "AX1zRInC_TA"] },
  { title: "Balenci", artist: "Shubh", year: 2025, youtubeIds: ["nt5tXl9Vtug"] },
  { title: "Together", artist: "Shubh", year: 2025, youtubeIds: ["7iy8iB8tu5c"] },
  { title: "Barota", artist: "Sidhu Moose Wala", year: 2025, youtubeIds: ["XpF9_3qih4k"] },
  { title: "Lock", artist: "Sidhu Moose Wala", year: 2025, youtubeIds: ["_wfrNbLguWw"] },
  { title: "Take Notes", artist: "Sidhu Moose Wala", year: 2025, youtubeIds: ["EdxguQAXeoU"] },
  { title: "0008", artist: "Sidhu Moose Wala", year: 2025, youtubeIds: ["uKAPYLvDJFQ"] },
  { title: "Neal", artist: "Sidhu Moose Wala", year: 2025, youtubeIds: ["TP0pxZ1EszM"] },
  { title: "Aadat", artist: "Yo Yo Honey Singh ft. AP Dhillon", year: 2025, youtubeIds: ["lcw4TDMBjZA"] },
  { title: "Thodi Si Daaru", artist: "AP Dhillon ft. Shreya Ghoshal", year: 2025, youtubeIds: ["slM5s55Jz0k"] },
  { title: "Sawaal Puchdi", artist: "Yo Yo Honey Singh x Bohemia", year: 2025, youtubeIds: ["472GGh5D_h8"] },
  { title: "Pan India", artist: "Guru Randhawa", year: 2025, youtubeIds: ["e2l7t1dzE8g"] },
  { title: "Kithe Vasde Ne", artist: "Guru Randhawa", year: 2025, youtubeIds: ["TUuTzp8Tmu0"] },
  { title: "Young G.O.A.T", artist: "Cheema Y", year: 2025, youtubeIds: ["uz6oyGKGvNo"] },
  { title: "Jindey", artist: "Arjan Dhillon x MXRCI", year: 2025, youtubeIds: ["LaEurVYTXGk"] },
  { title: "BIG THINGS", artist: "Jordan Sandhu x Gur Sidhu", year: 2025, youtubeIds: ["1iRfF-euP80"] },
  { title: "ACE", artist: "Shubh", year: 2026, youtubeIds: ["o-iWYlgdUHw"] },
  { title: "Bounce", artist: "Shubh", year: 2026, youtubeIds: ["yi-P8HCFtyw"] },
  { title: "Baller", artist: "Shubh", year: 2026, youtubeIds: ["xR3V5Ow2dTI"] },
  { title: "Moves", artist: "Shubh", year: 2026, youtubeIds: ["w-tlQtHWJt4"] },
  { title: "5-7", artist: "Karan Aujla", year: 2026, youtubeIds: ["omWV2zs1B2I"] },
  { title: "C Walk", artist: "Karan Aujla", year: 2026, youtubeIds: ["RJLm5-QL61A"] },
  { title: "Feel The Flava", artist: "Karan Aujla x Tru-Skool", year: 2026, youtubeIds: ["BmotKAKmJ2c"] },
  { title: "Ranjha", artist: "Diljit Dosanjh ft. Sia x David Guetta", year: 2026, youtubeIds: ["9wTEmuv6SvU", "fTpKWImEx84"] },
  { title: "Dealer", artist: "Diljit Dosanjh", year: 2026, youtubeIds: ["YwtvQ23_-34"] },
  { title: "Morni", artist: "Diljit Dosanjh x Tru-Skool", year: 2026, youtubeIds: ["5meceygQZ-s"] },
  { title: "5 Taara", artist: "Diljit Dosanjh ft. Tris Dhaliwal", year: 2026, youtubeIds: ["LmELgBJ4gfs"] },
  { title: "SINGH NAAL JODI", artist: "Diljit Dosanjh x Sukshinder Shinda", year: 2026, youtubeIds: ["aV_wFnXvZQA"] },
  { title: "Eyes On Me", artist: "Sidhu Moose Wala", year: 2026, youtubeIds: ["lJZ8wWCnwow"] },
  { title: "CEO", artist: "Cheema Y x Gur Sidhu", year: 2026, youtubeIds: ["fHE2rqtF_n8"] },
  { title: "Thinking Of You", artist: "AP Dhillon", year: 2026, youtubeIds: ["uTZ1JqiQPk4"] },
  { title: "DOPAMINE", artist: "Guru Randhawa", year: 2026, youtubeIds: ["S73QCB1PF6s"] },
  { title: "Headliner", artist: "Navaan Sandhu", year: 2026, youtubeIds: ["GE6w7DRyqcM"] },
  { title: "VPO", artist: "Mankirt Aulakh x Sultaan", year: 2026, youtubeIds: ["V_-0eeBS1gI"] }
];